### ISSUE TITLE
Add option to create reusable sockets

### ISSUE THREAD

**Issue by bablokb** [adafruit/Adafruit_CircuitPython_ConnectionManager#3]
According to the release-notes for CP 9.0.0:

- Incompatible change: Require explicit socket port reuse. Use `socket.setsockopt(pool.SOL_SOCKET, pool.SO_REUSEADDR, 1)`, as in CPython.

you have to explicitly mark sockets for reuse. Currently, user code has to create a session, call `get` and then manipulate the socket from the `Response`-object.

I think it would be much simpler to have this rather low-level manipulation of sockets as part of ConnectionManager. Or even better, as part of `socketpool` as the factory of sockets. But the latter would need changes to CP itself.

**Comment by justmobilize** [comment]
@tannewt do you think this would be a good idea? Where we [set the timeout](https://github.com/adafruit/Adafruit_CircuitPython_ConnectionManager/blob/a37193847e3c7e9a4e5b9b3f893f0147df30cbad/adafruit_connection_manager.py#L268), we could also check the CP version and if it's greater than 9, set this option

**Comment by anecdata** [comment]
I've been wrestling with trying to understand the socket reuse issue, there's a lot of history in the core issues and PRs, and a lot of unclear info out on the ethers.

My understanding is that `SO_REUSEADDR` used to be always set for `listen`-ing sockets [implicitly](https://github.com/adafruit/circuitpython/pull/7119), but now it needs to be done [explicitly](https://github.com/adafruit/circuitpython/pull/8940) (better Python compatibility). But is setting `SO_REUSEADDR` something that _only_ applies to servers / `listen`, or would there be benefit (or at least no side effects) of setting it for all sockets?

**Comment by dhalbert** [comment]
Yes, `SO_REUSEADDR` would be set for server-side sockets. You'd set it before `bind()`, which is before `listen()`. I don't know of a purpose for using it on the client set, in `adafruit_requests`.

Server examples that set `SO_REUSEADDR`:
https://www.codementor.io/@joaojonesventura/building-a-basic-http-server-from-scratch-in-python-1cedkg0842#sending-http-responses-using-sockets
https://medium.com/@stephen.biston/write-an-http-server-from-the-ground-up-in-9-minutes-with-python-1fdb9800a26a
etc.

**Comment by justmobilize** [comment]
Ahh, so we wouldn't add that here, unless we added support for getting server-side sockets in connection manager

**Comment by anecdata** [comment]
I was actually wondering about that this morning... was going to see if CM meshed with adafruit_http_server.

**Comment by dhalbert** [comment]
> Ahh, so we wouldn't add that here, unless we added support for getting server-side sockets in connection manager

That does not seem necessary to me. `adafruit_httpserver` takes a socket pool as an argument and takes care of getting a socket and setting it for reuse: https://github.com/adafruit/Adafruit_CircuitPython_HTTPServer/blob/dc9f83cd1a212520f4728dc3025dc881ffad3035/adafruit_httpserver/server.py#L207. That is typically the server's job.

I would suggest closing this issue unless, @bablokb, you have a particular use case in mind. The point of connection manager to me is to wrap and hide the multiple sources of socket **pools** and ssl contexts.

**Comment by bablokb** [comment]
Thanks for the clarification, it was not clear for me that this is not an issue for the client side.
