### ISSUE TITLE
Readme circup install instructions typo

### ISSUE THREAD

**Issue by somenice** [adafruit/Adafruit_CircuitPython_ConnectionManager#4]
Small issue on readme
I believe it should read `circup install adafruit_connection_manager`
instead of `circup install adafruit_connectionmanager`

**Comment by somenice** [comment]
Nevermind, looks like it works either way.
```
Searching for dependencies for: ['adafruit_connectionmanager']
Ready to install: ['adafruit_connection_manager']

'adafruit_connection_manager' is already installed
```

**Comment by dhalbert** [comment]
It _is_ a typo, since only `import adafruit_connection_manager` is correct. But the name matching in circup is forgiving. Reopening to fix.
